pages/contribute.md
=> typo in contribute page

_posts/2017-08-25-open-for-business.md
Shout-out to @QuentinFelix for spotting and fixing this 👍
=> Typo, merging in fix

pages/docs/designer/tutorial/part-2.md
that was not sooo obvius to me
=> adding the adress to use the sampler 

pages/docs/site/howto/add-showase.md
the title for showcase by pattern overview page was
=> corrected a copy paste typo

pages/docs/core/classdocs/src/part.md
quick update before the bug is fixed (hohoho is that going to give me a new badge =P ) Oh no, the badge is for finding the bug, not solving it
=> shifttowards $distance description

js/app.js
Hat-tip to @PD75 for reporting this
=> Fixed issue in draft scope and added cache busting

img/donations.svg
Thanks to @Pixieish for the contributed changes 👍
=> Typo fixes and donations update

img/donations.svg, pages/docs/designer/tutorial/part-2.md
Thanks to @Pixieish for the PR and pointing this out in the first place
=> Fixes to the design tutorial

_data/freesewing.yaml, _layouts/pattern.html, json/freesewing.json
=>  Limited bounds of Aaron's shoulderStrapPlacement option 

pages/docs/infrastructure.md
=> Added link to the status page on the infrastructure page

pages/docs/core/classdocs/src/part.md
=> Added list of available snippets to class documentation

pages/docs/designer/tutorial/part-2.md
fixed some typos I found while following the Baby Bib tutorial
=> fixed some typos

pages/docs/core/classdocs/src/part.md
Thanks to @QuentinFelix for collecting my Gitter ramblings in a PR 👍
=> Added rules for naming offset path points

_config.yml, _config/develop.yml, _headers
=> Added netlify headers file

pages/about/index.md, pages/docs/fundamentals.md
=>  Update to fundamentals.md 

pages/docs/patterns/simon/index.md
This PR includes two commits. The first is purely cosmetic and involved just running `index.md` through `aspell`. The second, though, confused me a bit last night as I was assembling my first "real" Simon. I made a guess about which bends up vs down, happy to update the PR if I got it wrong.
=> Minor improvements to Simon docs

_assets/css/freesewing/_comments.scss, _assets/css/freesewing/_tweaks.scss, _assets/js/freesewing/base.js.liquid, js/app.js, pages/components/account/settings.md, pages/show-user.md
Fixes #184 
Also includes fix to allow deep-linking to comments.
=> Merging in social media support

_assets/js/freesewing/base.js.liquid
=> Added check for undefined comment.social

js/app.js
=> Added check for undefined data.social

js/app.js
=> Check for null value on data.social

js/app.js
=> Yet another fix for null social media data

js/app.js
=> Yet another fix for null social media data coz I'm an idiot

_assets/css/freesewing/_comments.scss, _assets/js/freesewing/base.js.liquid, _includes/pattern-options/aaron/stretchfactor.html, js/app.js, js/welcome.js, pages/components/account/settings.md, pages/welcome.md
Fixed outdated instructions for stretch factor option in Aaron
=>  Added GitHub to social account, and social to welcome modal 

pages/docs/core/classdocs/src/utils.md
=> Added doc for Utils::asPointArray (#181)

pages/docs/patterns/cathrin/index.md
Outlined fabric options, and directin readers to two exceptional sites
=> Added basic corset advice

_includes/measurements/acrossback.html
based on feedback from @rkat2836
=> Updated across back measurement instructions 

img/donations.svg
=> Updated donations img

pages/patterns/benjamin.md
=> Added some Benjamins to fork. Fixes #198

pages/patterns/benjamin.md
=> Corrected mis-named draft in Benjamin fork list

_data/freesewing.yaml, json/freesewing.json
=> Updated prefetch data from core v1.2.5

pages/tools/index.md
=> Added tools index page

_headers, _includes/end-page.html, _includes/side-menu.html, _includes/top-menu.html, _posts/2017-06-16-privacy-choices.md, js/homepage.js
=> Content Security Policy

_headers
=> CSP broke jQuery

_assets/css/freesewing/_comments.scss
=> Hiding overflow on comments to keep mobile width in check

_posts/2017-12-06-florent-flat-cap-beta.md
One change didn't make it through I guess
=> change Felix into Quentin

js/patronlist.js
=> Sorting of patron list

pages/docs/core/install.md, pages/docs/designer/tutorial/install.md, pages/docs/designer/tutorial/part-1.md
=> Added design tutorial install instructions

pages/docs/designer/tutorial/install.md
=> Fixed faulty test URL

pages/docs/patterns/bruce/index.md
=> Bruce video episode 1 is back from the death

_includes/footer.html
=> Fixed broken gitter link

pages/docs/designer/tutorial/install.md, pages/docs/designer/tutorial/part-1.md
=> Tweak to designer tutorial

_assets/js/freesewing/base.js.liquid
=> Fixed issue where login wasn't properly detected

_assets/js/freesewing/base.js.liquid
=> Typo fix in designer tutorial

_posts/2017-12-20-announcing-carlton-and-bent.md
=> Added link to carlton pattern page in blog post

pages/docs/measurements/naturalwaisttofloor.md
=> Added missing natural waist to floor docs page

_assets/css/freesewing/_thematic.scss
=> Fixed value for .bg-thematic fallback background colour

_data/freesewing.yaml, json/freesewing.json
=> Core version update

pages/docs/core/classdocs/src/part.md
=> Moved  to the correct location in classdocs

js/admin.js, js/app.js, pages/docs/core/classdocs/patterns/core/pattern.md, pages/docs/core/install.md
=>  Fix for broken model management 

js/app.js
=> Fix for signup issue

index.md, pages/status.md
=> Put up warning about JSON issues

js/homepage.js, js/welcome.js
=>  Fix for welcome.js 

js/app.js
=> Fix for missing model data

_assets/js/freesewing/bail.js.liquid
=> Fixed bail inclusion

_assets/js/freesewing/bail.js.liquid
=> Forced bail inclusion

_posts/2018-01-26-announcing-carlita.md
=> Small blog post fixes

_posts/2018-01-26-announcing-carlita.md
=> Fixed typo

_includes/pattern-options/carlita/armholedepthfactor.html, _includes/pattern-options/carlita/chestease.html, _includes/pattern-options/carlita/cuffease.html, _includes/pattern-options/carlita/hipsease.html, _includes/pattern-options/carlita/seatease.html, _includes/pattern-options/carlita/shoulderease.html, _includes/pattern-options/carlita/sleevebend.html, _includes/pattern-options/carlita/sleevecapease.html, _includes/pattern-options/carlita/sleevecapheightfactor.html, _includes/pattern-options/carlita/sleevelengthbonus.html, _includes/pattern-options/carlita/waistease.html
=> Updated samples for carlita

_includes/measurementTabs.html, pages/docs/core/classdocs/src/part.md, pages/docs/measurements/bustspan.md, pages/docs/measurements/highbust.md, pages/docs/measurements/highpointshouldertobust.md
=> More carlita fixes

_assets/css/_freesewing.scss, _assets/js/bundle.js
=> Disabled lightbox

_assets/js/freesewing/base.js.liquid
=> removed lighbox config

pages/snippets/login/form.md
=> Removing clashing IDs in login form

_data/freesewing.yaml, json/freesewing.json
=> Updated site data after core version bump 

_data/freesewing.yaml, json/freesewing.json
=> Prefetch data update for core 1.6.2

_data/freesewing.yaml, json/freesewing.json
=> Prefetch data update for core 1.6.3

_data/freesewing.yaml, _includes/pattern-options/sven/ribbing.html, _includes/pattern-options/sven/ribbingheight.html, _includes/pattern-options/sven/ribbingstretchfactor.html, json/freesewing.json, pages/components/pattern-options/sven/ribbing.md, pages/components/pattern-options/sven/ribbingheight.md, pages/components/pattern-options/sven/ribbingstretchfactor.md
=> Updated sven options

_data/freesewing.yaml, json/freesewing.json
=> Fixed typo in sven config

_layouts/pattern.html, pages/docs/patterns/cathrin/index.md, pages/patterns/cathrin.md
=> Updated pattern layout and credit for Cathrin

Gemfile, Gemfile.lock
=> Clawing my way out of gemhell

_includes/start-page.html
=> Fixed faulty CSS asset include

pages/docs/patterns/carlita/index.md
=> Added Anneke's notes on making Carlita

README.md, _layouts/showcase-maker.html, _layouts/showcase.html, _showcases/2018-01-02-outfit-wahid-theodore-florent-by-paul.md, _showcases/2018-01-02-outfit-wahid-theodore-simon-by-paul.md, pages/docs/patterns/carlita/index.md, pages/showcase/index.md
=>  Showcases support multiple patterns + carlita docs update 

pages/patrons/join.md
=> Added yearly signup for patrons

_data/freesewing.yaml, json/freesewing.json
=> Prefetch data update

_showcases/2018-03-05-speckles-simon.md
=> Fixed typo in maker name
